# Generated by Django 5.1 on 2024-10-30 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_categoria_foto_produto_delete_todo_foto_produto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="descricao_categoria",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="categoria",
            old_name="nome_categoria",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="descricao_produto",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="nome_produto",
            new_name="nome",
        ),
        migrations.AddField(
            model_name="produto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoria",
                to="ecommerce.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name="Foto",
        ),
    ]
